spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.yandex.ru
    port: 587
    username: nlojiol
    password: 46531563156
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  application:
      name: notification-service
  config:
      import: optional:configserver:http://localhost:8888
      kafka:
        bootstrap-servers: localhost:9092

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  resilience4j:
    circuitbreaker:
      instances:
        emailService:
          registerHealthIndicator: true
          slidingWindowSize: 5
          failureRateThreshold: 50

server:
  port: 8081