server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 31415
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  application:
      name: user-service
  config:
      import: optional:configserver:http://localhost:8888
  cloud:
      discovery:
         enabled: true
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
        userService:
           registerHealthIndicator: true
           slidingWindowSize: 10
           failureRateThreshold: 50
kafka:
  bootstrap-servers: localhost:9092
  topic: user-events
