server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/your-config-repo
          default-label: main
          lone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka